<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>
    <link href="{{ this.config.cssUrl }}bootstrap.min.css" rel="stylesheet">
    <link href="{{ this.config.cssUrl }}loading.min.css" rel="stylesheet">
    <link href="{{ this.config.cssUrl }}tweetsmap.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="{{ this.config.diUrl }}favicon.png" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{{ this.config.jsUrl }}jquery.min.js"></script>
    <script type="text/javascript">
     var baseUrl = '{{ this.config.baseUrl }}';
    </script>
  </head>
  <body>