<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tweets Map</title>
    <link href="{{ cssUrl }}bootstrap.min.css" rel="stylesheet">
    <link href="{{ cssUrl }}loading.min.css" rel="stylesheet">
    <link href="{{ cssUrl }}tweetsmap.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="{{ diUrl }}favicon.png" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{{ jsUrl }}jquery.min.js"></script>
<!--     <script src="{{ jsUrl }}tweetsmap.js"></script> -->
  </head>
  <body>
    <div class="list-group">
        {% if histories[0] is empty %}
            {% set backUrl = baseUrl %}
        {% else %}
            {% set backUrl = baseUrl ~ "q=" ~ histories[0] %}
        {% endif %}
        <a href="{{ backUrl }}" class="list-group-item history-list"><< BACK TO THE TWEETS!</a>
        {% for history in histories %}
            <a href="{{ baseUrl }}?q={{ history }}" class="list-group-item history-list">{{ history }}</a>
        {% endfor  %}
    </div>
    <script src="{{ jsUrl }}bootstrap.min.js"></script>
    <script src="{{ jsUrl }}loading.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ jsUrl }}ie10-viewport-bug-workaround.js"></script>
  </body>
</html>